alias tmux='_my_tmux try-attach'

alias t='tmux'
alias ta='_my_tmux attach'
alias tat='_my_tmux attach'
alias tls='tmux ls'
alias tnew='_my_tmux new'
alias tas='_my_tmux attach-select'
alias trs='tmux-resume'

alias ta0='_my_tmux attach 0'
alias ta1='_my_tmux attach 1'
alias ta2='_my_tmux attach 2'
alias ta3='_my_tmux attach 3'
alias ta4='_my_tmux attach 4'
alias ta5='_my_tmux attach 5'
alias ta6='_my_tmux attach 6'
alias ta7='_my_tmux attach 7'
alias ta8='_my_tmux attach 8'
alias ta9='_my_tmux attach 9'
