"""
Simple utility to generate Aerospace modes for setting and focusing marks. This
way I can just hit, say, `semihyper+m x` to mark the current window and
`semihyper+' x` to go back to it. This saves at least one whole keystroke(!!)
compared to the simpler option of showing an AppleScript or choose-gui window to
prompt for a mark, which requires hitting enter after pressing the mark key.

Currently, only marks comprised of a single uppercase or lowercase ASCII letter
are supported.

Usage:
    python .config/aerospace/utils/generate_marks_mode.py | pbcopy
"""
import string


def main():
    # We could use tomllib to generate this, but this way works on the old
    # Python version bundled with macOS and it gives more control over how the
    # result is formatted.
    print('## MARK: focus-mark mode')
    print('## auto-generated by utils/generate_marks_mode.py')
    print('[mode.set-mark.binding]')
    print("    esc = 'mode main'")
    for char in string.ascii_lowercase:
        print(f'    {char} = ["exec-and-forget aerospace-marks mark {char}", "mode main"]')
        print(f'    shift-{char} = ["exec-and-forget aerospace-marks mark {char.upper()}", "mode main"]')

    print()

    print('## MARK: focus-mark mode')
    print('## auto-generated by utils/generate_marks_mode.py')
    print('[mode.focus-mark.binding]')
    print("    esc = 'mode main'")
    for char in string.ascii_lowercase:
        print(f'    {char} = ["exec-and-forget aerospace-marks focus {char}", "mode main"]')
        print(f'    shift-{char} = ["exec-and-forget aerospace-marks focus {char.upper()}", "mode main"]')


if __name__ == '__main__':
    main()
